--
---- Dados iniciais de funcionario
--INSERT INTO funcionario (id, nome, email, senha, supervisor_id, cargo, especialidade)
--VALUES
--    (1, 'Dra. Helena Castro', 'helena.castro@clinica.com', 'SenhaForte@2024', NULL,
--     'Supervisora de Fonoaudiologia', 'Motricidade Orofacial'),
--
--    (2, 'Juliana Almeida', 'admin@clinica.com', '$2a$10$0/TKTGxdREbWaWjWYhwf6e9P1fPOAMMNqEnZgOG95jnSkHSfkkIrC', 1,
--     'Fonoaudióloga', 'Linguagem Infantil'),
--
--    (3, 'Marcos Ribeiro', 'marcos.ribeiro@clinica.com', 'SenhaForte@2024', 2,
--     'Fonoaudiólogo', 'Voz e Reabilitação Vocal'),
--
--    (4, 'Carla Menezes', 'carla.menezes@clinica.com', 'SenhaForte@2024', 1,
--     'Fonoaudióloga', 'Audiologia e Processamento Auditivo'),
--
--    (5, 'Charles Oliveira', 'charles.oliveira@clinica.com', 'SenhaForte@2024', 1,
--     'Fonoaudióloga', 'Audiologia e Processamento Auditivo'),
--
--    (6, 'Dra. Marina Castro', 'marina.castro@clinica.com', 'SenhaForte@2024', NULL,
--     'Supervisora de Terapia', 'Motricidade Orofacial');
--
---- Inserção de pacientes com convenio e data_inicio (data do cadastro)
--INSERT INTO paciente (nome, email, cpf, telefone, dt_nascimento, convenio, data_inicio)
--VALUES
--   ('Lucas Silva', 'lucas.silva@email.com', '123.456.789-00',  '(11) 91234-5678', '1990-05-15', 'Sul America', CURRENT_DATE),
--   ('Mariana Costa', 'mariana.costa@email.com', '987.654.321-00',  '(21) 99876-5432', '1985-11-22', 'Bradesco Saúde', CURRENT_DATE),
--   ('Pedro Oliveira', 'pedro.oliveira@email.com', '456.789.123-11',  '(31) 91234-8765', '1978-02-10', 'Unimed', CURRENT_DATE),
--   ('Ana Paula Lima', 'ana.lima@email.com', '321.654.987-22',  '(41) 98765-4321', '1992-08-30', 'NotreDame Intermédica', CURRENT_DATE),
--   ('Rafael Souza', 'rafael.souza@email.com', '654.321.987-33',  '(51) 91234-0987', '1988-03-12', 'Porto Saúde', CURRENT_DATE);
--
---- Tabela intermediária funcionario_roles (caso ainda não exista)
--CREATE TABLE IF NOT EXISTS funcionario_roles (
--    funcionario_id BIGINT NOT NULL,
--    role_id BIGINT NOT NULL,
--    PRIMARY KEY (funcionario_id, role_id),
--    FOREIGN KEY (funcionario_id) REFERENCES funcionario(id) ON DELETE CASCADE,
--    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
--);
--
---- Roles básicas
--INSERT INTO role (nome) VALUES
--    ('ADMIN'),
--    ('USER'),
--    ('MANAGER');
--
---- Associação funcionário -> role
--INSERT INTO funcionario_roles (funcionario_id, role_id) VALUES
--    (1, 3), -- Helena é MANAGER
--    (2, 1), -- Juliana (admin@clinica.com) é ADMIN
--    (3, 2), -- Marcos é USER
--    (4, 2), -- Carla é USER
--    (5, 2), -- Charles é USER
--    (6, 3); -- Marina é MANAGER
